version: '3'
services:
  client:
    image: josedv1/pos-system:client
    ports:
      - "4321:4321"
    depends_on:
      - server
    environment:
      - PUBLIC_API_URL=http://server:3000/api
  server:
    image: josedv1/pos-system:server
    environment:
      - DATABASE_URL=postgres://postgres:possystem1001446301!@db:5432/pos_system_db
    ports:
      - "3000"
    depends_on:
      - db
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=possystem1001446301!
      - POSTGRES_DB=pos_system_db
    ports:
      - "5433:5432"
      
    
    
