version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - server
    environment:
      - PUBLIC_API_URL=http://server:3000/api
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:possystem1001446301!@db:5432/pos_system_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=possystem1001446301!
      - POSTGRES_DB=pos_system_db
    ports:
      - "5432:5432"
    volumes:
      - ./pos_system_db_data:/var/lib/postgresql/data
